import type {
  AgentCapabilities,
  AgentDetection,
  AgentId,
  AgentModelOption,
  ApprovalDecision,
  ApprovalRequest,
  ChangedFile,
  CodexModelCatalogResult,
  CreateSessionInput,
  Diagnostics,
  DiffResult,
  ExecutableTestResult,
  HandoffExecuteInput,
  LaunchTerminalResult,
  Session,
  SessionWithMessages,
  Settings,
  SettingsPatch,
  TerminalExitInfo,
  Workspace
} from './types'
import type { AgentEvent } from './events/agent-event'
import type { TraceEvent } from './events/trace-event'

export type Unsubscribe = () => void

/** What onEvent delivers — the event plus the envelope's dedup/tracing
 *  metadata (see SessionEventEnvelope). */
export interface SessionEventPayload {
  event: AgentEvent
  sequence: number
  eventId: string
}

/**
 * The full surface exposed on `window.agentDock` by the preload script.
 * The renderer never talks to Electron/Node directly — this is the only
 * contract it depends on.
 */
export interface AgentDockApi {
  workspace: {
    open(): Promise<Workspace | null>
    list(): Promise<Workspace[]>
    getCurrent(): Promise<Workspace | null>
    close(): Promise<void>
  }
  agents: {
    list(): Promise<AgentDetection[]>
    detect(agentId: AgentId): Promise<AgentDetection>
    setCustomPath(agentId: AgentId, customPath: string | null): Promise<AgentDetection>
    getCapabilities(agentId: AgentId): Promise<AgentCapabilities>
    /** Opens a native file picker for choosing an executable override.
     *  Returns null if the user cancels. */
    browseExecutable(agentId: AgentId): Promise<string | null>
    /** Validates one specific path directly — used by the Settings "Test"
     *  button, independent of whatever is currently saved as the custom
     *  path or auto-detected. */
    testExecutable(agentId: AgentId, path: string): Promise<ExecutableTestResult>
  }
  codex: {
    /** Fast, non-blocking — returns the cached catalogue (or a
     *  currently-configured-model fallback) without spawning anything.
     *  Safe to call on every render. */
    getModelCatalog(): Promise<CodexModelCatalogResult>
    /** Does a real live fetch against Codex's app-server `model/list` and
     *  updates the cache — used at app start, on the Settings "Refresh"
     *  action, and the Model menu's own refresh button. */
    refreshModelCatalog(): Promise<CodexModelCatalogResult>
  }
  claude: {
    /** Fast, non-blocking — returns the cached (or plain static,
     *  reasoning-effort-unenriched) model list without spawning anything. */
    getModelCatalog(): Promise<AgentModelOption[]>
    /** Does a real live fetch against Claude Agent SDK's
     *  Query.supportedModels() and updates the cache. */
    refreshModelCatalog(): Promise<AgentModelOption[]>
  }
  session: {
    create(input: CreateSessionInput): Promise<Session>
    list(workspaceId: string): Promise<Session[]>
    get(sessionId: string): Promise<SessionWithMessages | null>
    /** `turnId` is generated by the renderer (crypto.randomUUID()) and
     *  becomes the id every AgentEvent for this turn carries — it's what
     *  lets the shared reducer scope events to the right turn (see
     *  AgentEventReducer's `isForActiveTurn`). */
    sendPrompt(sessionId: string, text: string, turnId: string): Promise<void>
    interrupt(sessionId: string): Promise<void>
    stop(sessionId: string): Promise<void>
    delete(sessionId: string): Promise<void>
    onEvent(sessionId: string, cb: (payload: SessionEventPayload) => void): Unsubscribe
    /** Debug instrumentation only (Testing Mode) — never carries prompt/reply
     *  text, see TraceEvent. */
    onTrace(sessionId: string, cb: (trace: TraceEvent) => void): Unsubscribe
    /** Answers an interaction_required prompt — never appears as an ordinary
     *  chat message. */
    respondToInteraction(sessionId: string, interactionId: string, optionId: string): Promise<void>
    /** Live model switch (only meaningful if the agent's capabilities report
     *  supportsLiveModelSwitch). */
    setModel(sessionId: string, modelId: string): Promise<void>
    /** Runs a native agent command (from capabilities.commands) — never
     *  appears as an ordinary chat message. */
    runCommand(sessionId: string, commandId: string): Promise<void>
    /** Opens a brand-new, independent interactive terminal in the session's
     *  workspace — never a reattachment to this session's own live process
     *  (no such reattachment exists). Surfaces failure via the returned
     *  result rather than failing silently. */
    openExternalTerminal(sessionId: string): Promise<LaunchTerminalResult>
  }
  git: {
    changedFiles(workspaceId: string): Promise<ChangedFile[]>
    diff(workspaceId: string, path: string): Promise<DiffResult>
    branch(workspaceId: string): Promise<string | null>
    revertFile(workspaceId: string, path: string): Promise<void>
  }
  /** Backs the rich Markdown renderer's link/image affordances — every
   *  method is workspace-scoped and path-validated main-process-side (see
   *  media-service.ts); the renderer never gets unrestricted filesystem
   *  access. */
  media: {
    resolveImage(workspaceId: string, path: string): Promise<{ dataUrl?: string; error?: string }>
    revealInFolder(workspaceId: string, path: string): Promise<{ ok: boolean; error?: string }>
    openLocalPath(workspaceId: string, path: string): Promise<{ ok: boolean; error?: string }>
    /** Opens in the OS default browser — never inside the Electron window.
     *  Only http/https are honored; see media-service.ts. */
    openExternalLink(url: string): Promise<{ ok: boolean; error?: string }>
  }
  approvals: {
    respond(approvalId: string, decision: ApprovalDecision): Promise<void>
    onRequest(cb: (request: ApprovalRequest) => void): Unsubscribe
  }
  settings: {
    get(): Promise<Settings>
    update(patch: SettingsPatch): Promise<Settings>
    getDiagnostics(): Promise<Diagnostics>
  }
  terminal: {
    write(sessionId: string, data: string): void
    resize(sessionId: string, cols: number, rows: number): void
    interrupt(sessionId: string): void
    onData(sessionId: string, cb: (data: string) => void): Unsubscribe
    onExit(sessionId: string, cb: (info: TerminalExitInfo) => void): Unsubscribe
  }
  handoff: {
    generateSummary(sessionId: string): Promise<string>
    execute(input: HandoffExecuteInput): Promise<Session>
  }
  windowCtl: {
    minimize(): void
    maximize(): void
    close(): void
    isMaximized(): Promise<boolean>
    onMaximizeChange(cb: (isMaximized: boolean) => void): Unsubscribe
  }
}

declare global {
  interface Window {
    agentDock: AgentDockApi
  }
}
